# Generated by Django 3.0.7 on 2020-09-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200902_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestampe',
            new_name='timestamp',
        ),
    ]
